pipeline {
  agent {
    docker { image 'node:16-alpine' 
    registryCredentialsId 'dockercred'
    registryUrl 'https://docker.io'
           }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
