pipeline {
  agent any
  environment {
    PATH = "/usr/share/maven/bin:$PATH"
  }
  stages{
    stage("test") {
      steps{
      echo "i am creating a file"
      }
    }
     stage("mvn check") {
      steps{
        echo "this is checking with mvn"
        sh "mvn clean package"
      }
    }
  }
}
