pipeline {
  agent {
    docker {
    registryCredentialsId 'dockercred'
    registryUrl 'https://docker.io'
           }
  }
  stages {
    stage('Test') {
      steps {
        sh 'docker --version'
      }
    }
  }
}
